# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CostCenterSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseCore', '~> 10.22'
  pod 'Alamofire', '~> 5.9'
  # Pods for CostCenterSDK

  target 'CostCenterSDKTests' do
    # Pods for testing
  end

end
